### ISSUE TITLE
Ditch PHP 5.4 and PHP 5.5 support

### ISSUE THREAD

**Issue by unreal4u** [McFizh/libMQTT#9]
PHP 5.4 and PHP 5.5 are no longer supported in any way by PHP, not even security updates: 
http://php.net/supported-versions.php

In fact, PHP 5.6 only has security updates for now and is no longer actively supported as well.

I can't speak for everybody, but I personally ditched the PHP5 versions long ago (and at work we are able to work with the latest PHP version). Some references:
* [PHPUnit](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.2.0) is doing the same for quite some time now.
* [Symfony](https://twitter.com/fabpot/status/809743412715016192) will follow the same rule.
* Oh and [Laravel as well](https://twitter.com/taylorotwell/status/809767371774816256).

I'm running into some problems while unit testing because of stuff the old PHP didn't support back then: https://travis-ci.org/McFizh/libMQTT/builds/241611664?utm_source=github_status&utm_medium=notification

This won't be the last problem I'll run into, and I pretend to do quite some improvements :)

Any objection to bump up the minimum required PHP version? I'm more than happy to make the PR :)

Greetings.

**Comment by McFizh** [comment]
I can hardly see any reason to bump minimum PHP version from 5.4 to 5.6 (for example), at least not in the near future (within year 2017 or so). Transition doesn't really bring any features that are vital for this library, but just reduces the userbase.

For example Centos 7 repo seems to have PHP version 5.4.16 and Ubuntu 14.04 repo has PHP version 5.5.9 . Both distros have more than 2 years before their support ends.

Although if travis drops support for PHP 5.4/5.5, then I'm somewhat forced to switch to PHP 5.6, as automated testing becomes impossible.
